"use client"

// Import necessary icons
import { FaGithub, FaLinkedinIn, FaTwitter, FaInstagram, FaDownload } from "react-icons/fa"
import { HiMail, HiOutlineLocationMarker, HiOutlineDeviceMobile } from "react-icons/hi"
import { IoMdBriefcase, IoMdNotifications } from "react-icons/io"

// 1. RE-INTRODUCED THE CORRECT IMPORT USING THE EXACT FILE NAME
//    (Based on your file structure: src/assets/snehaResume.pdf)
import snehaResumePdf from "../assets/snehaResume.pdf"; 

const Footer = () => {
  const currentYear = new Date().getFullYear()
  const jobTitle = "MERN Stack Developer"

  const socialLinks = [
    { name: "GitHub", icon: FaGithub, url: "https://github.com/sneha-bhardwaj7" },
    { name: "LinkedIn", icon: FaLinkedinIn, url: "https://www.linkedin.com/in/sneha-bhardwaj-764b38290/" },
    { name: "Email", icon: HiMail, url: "snehabhardwaj083@gmail.com" },
  ]

  const quickLinks = [
    { name: "Home", href: "#home" },
    { name: "About", href: "#about" },
    { name: "Skills", href: "#skills" },
    { name: "Projects", href: "#projects" },
    { name: "Experience", href: "#experience" },
    { name: "Education", href: "#education" },
    { name: "Contact", href: "#contact" },
  ]

  // 2. CORRECTED handleDownloadResume logic
  const handleDownloadResume = () => {
    // Use the imported variable, which contains the correct URL generated by Vite/the bundler.
    const resumeUrl = snehaResumePdf; 
    
    const link = document.createElement("a")
    link.href = resumeUrl
    // Set the desired download name for the file
    link.setAttribute("download", "Sneha_Bhardwaj_Resume.pdf")
    
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" })
  }

  const scrollToSection = (sectionId) => {
    const element = document.getElementById(sectionId.replace("#", ""))
    if (element) {
      element.scrollIntoView({ behavior: "smooth" })
    }
  }

  return (
    <footer className="bg-gradient-to-br from-gray-900 to-black relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-purple-500/5 rounded-full blur-3xl floating-element"></div>
        <div
          className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-pink-500/5 rounded-full blur-3xl floating-element"
          style={{ animationDelay: "2s" }}
        ></div>
      </div>

      <div className="container mx-auto px-6 relative z-10">
        {/* Main Footer Content */}
        <div className="py-16">
          <div className="grid lg:grid-cols-4 md:grid-cols-2 gap-8">
            {/* Brand Section */}
            <div className="lg:col-span-2 slide-in-left">
              <div className="flex items-center space-x-3 mb-6">
                <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg flex items-center justify-center floating-element glow-effect">
                  <span className="text-white font-bold text-xl">S</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold gradient-text">Sneha Bhardwaj</h3>
                  {/* Updated job title */}
                  <p className="text-purple-400 font-medium flex items-center space-x-2">
                    <IoMdBriefcase className="inline" />
                    <span>{jobTitle}</span>
                  </p>
                </div>
              </div>

              <p className="text-gray-400 text-lg leading-relaxed mb-6 max-w-md">
                Passionate {jobTitle} creating beautiful, responsive, and user-friendly web applications. Always
                learning, always growing.
              </p>

              <div className="flex space-x-4">
                {socialLinks.map((social, index) => (
                  <a
                    key={social.name}
                    href={social.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-10 h-10 bg-gray-800 hover:bg-purple-600 rounded-full flex items-center justify-center transition-all duration-300 hover-lift glow-effect scale-in"
                    style={{ animationDelay: `${index * 0.1}s` }}
                  >
                    {/* Use the imported React Icon component */}
                    <social.icon className="text-white text-lg" />
                  </a>
                ))}
              </div>
            </div>

            {/* Quick Links */}
            <div className="slide-in-up">
              <h4 className="text-xl font-bold mb-6 gradient-text">Quick Links</h4>
              <ul className="space-y-3">
                {quickLinks.map((link, index) => (
                  <li key={link.name}>
                    <button
                      onClick={() => scrollToSection(link.href)}
                      className="text-gray-400 hover:text-white transition-all duration-300 hover:translate-x-2 block slide-in-right"
                      style={{ animationDelay: `${index * 0.1}s` }}
                    >
                      {link.name}
                    </button>
                  </li>
                ))}
              </ul>
            </div>

            {/* Contact Info */}
            <div className="slide-in-right">
              <h4 className="text-xl font-bold mb-6 gradient-text">Get In Touch</h4>
              <div className="space-y-4">
                {/* Email */}
                <div className="flex items-center space-x-3 text-gray-400">
                  <HiMail className="text-lg text-purple-400" />
                  <a
                    href="snehabhardwaj083@gmail.com"
                    className="hover:text-white transition-colors duration-300"
                  >
                    snehabhardwaj083@gmail.com
                  </a>
                </div>
                {/* Phone Number Updated */}
                <div className="flex items-center space-x-3 text-gray-400">
                  <HiOutlineDeviceMobile className="text-lg text-purple-400" />
                  <a href="tel:+917209547221" className="hover:text-white transition-colors duration-300">
                    +91 72095 47221
                  </a>
                </div>
                {/* Location */}
                <div className="flex items-center space-x-3 text-gray-400">
                  <HiOutlineLocationMarker className="text-lg text-purple-400" />
                  <span>India</span>
                </div>
              </div>

              {/* Download Resume Button with Functionality */}
              <div className="mt-6">
                <button 
                  onClick={handleDownloadResume} 
                  className="btn-primary px-6 py-3 hover-lift flex items-center space-x-2"
                >
                  <FaDownload className="text-white" /> {/* Download Icon */}
                  <span>Download Resume</span>
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Newsletter/Stay Updated Section - Fully Interactive Version */}
        {/* <div className="py-12 border-t border-gray-800 slide-in-up relative overflow-hidden"> */}
            {/* Interactive Background Glow */}
            {/* <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <div className="w-96 h-96 bg-purple-500/10 rounded-full blur-3xl opacity-50 animate-pulse-slow"></div>
            </div>
            
            <div className="text-center relative z-10">
                <h4 className="text-3xl font-extrabold mb-4 gradient-text flex items-center justify-center space-x-3">
                    <IoMdNotifications className="text-pink-500" />
                    <span>Stay Updated on MERN Stack Insights</span>
                </h4>
                <p className="text-gray-400 mb-8 max-w-xl mx-auto text-lg">
                    **Join the SnehaDev Digest!** Get exclusive content: latest articles, advanced tutorials, and **live project updates** directly focused on the **MERN Stack**.
                </p>
                <form 
                    onSubmit={(e) => {
                        e.preventDefault(); 
                        alert("Thank you for your interest! Subscription feature is coming soon.")
                    }}
                    className="flex flex-col sm:flex-row gap-3 justify-center max-w-lg mx-auto p-2 bg-gray-900/50 rounded-xl border border-gray-700/50 shadow-2xl"
                >
                    <input
                        type="email"
                        placeholder="Enter your email to join the dev community"
                        required
                        className="flex-1 px-5 py-3 bg-gray-800/80 border border-gray-600 rounded-lg focus:border-purple-500 focus:outline-none focus:ring-2 focus:ring-purple-500/50 text-white placeholder-gray-500 transition duration-300"
                    />
                    <button 
                        type="submit" 
                        className="btn-primary px-6 py-3 hover-lift transition duration-300 transform hover:scale-105 min-w-[150px]"
                    >
                        Subscribe Now
                    </button>
                </form>
                <p className="text-gray-500 text-sm mt-4">
                    *No spam, just quality MERN content delivered to your inbox. Unsubscribe anytime.*
                </p>
            </div>
        </div> */}

        {/* Bottom Footer */}
        <div className="py-8 border-t border-gray-800">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="text-gray-400 text-center md:text-left mb-4 md:mb-0 slide-in-left">
              <p>&copy; {currentYear} Sneha Bhardwaj. All rights reserved.</p>
              {/* <p className="text-sm mt-1">Built with ❤️ using React.js & Tailwind CSS</p> */}
            </div>

            <div className="flex items-center space-x-6 slide-in-right">
              <a href="#" className="text-gray-400 hover:text-white transition-colors duration-300 text-sm">
                Privacy Policy
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors duration-300 text-sm">
                Terms of Service
              </a>
              <button
                onClick={scrollToTop}
                className="w-10 h-10 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center hover-lift glow-effect transition-all duration-300"
              >
                <span className="text-white">↑</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}

export default Footer